export const enStrings = {
  app_name: "BookPad",
  success_update_publisher: "Update publisher successfully",
  add_new_publisher: "Add new publisher",
  add_new_book: "Add new book",
  success_create_publisher: "Create publisher successfully",
  filter: "Filter",
  search: "Search",
  author: "Author",
  status: "Status",
  books: "Books",
  add: "Add",
  save: "Save",
  edit: "Edit",
  publisher_name: "Publisher name",
  publisher_description: "Publisher description",
  publisher_name_required: "Publisher name is required",
  publisher_description_required: "Publisher description is required",
  missing_required_fields: "Missing required fields",
  title: "Title",
  publish_date: "Publish date",
  view_and_edit_book: "View and edit book",
  book_description: "Book description",
  add_new_author: "Add new author",
  view_author: "View author",
  edit_author: "Edit author",
  author_date_of_birth: "Author date of birth",
  author_date_of_death: "Author date of death",
  author_description: "Author description",
  author_name: "Author name",
  success_create_author: "Create author successfully",
  success_create_Category: "Create Category successfully",
  category_name: "Category name",
  category_description: "Category description",
  add_new_category: "Add new category",
  edit_category: "Edit category",
  view_category: "View category",
  category_id: "Category id",
  publisher_id: "Publisher id",
  author_id: "Author id",
  delete: "Delete",
  get_started: "Get started",
  go_back: "Go back",
  user_name: "User name",
  password: "Password",
  login: "Login",
  forgot_password: "Forgot password",
  dont_have_account: "Don't have an account?",
  sign_up: "Sign up",
  email: "Email",
  loginSuccess: "Login Success",
  loginSuccessMessage: "You have logged in successfully",
  ok: "OK",
  loginFailed: "Login Failed",
  hello: "Hello",
  for_you: "For you",
  best_sellers: "Best sellers",
  new_releases: "New releases",
  categories: "Categories",
  authors: "Authors",
  publishers: "Publishers",
  retry: "Retry",
  exit: "Exit",
  read: "Read",
  book_detail: "Book detail",
  error_occurred: "Error occurred. Please try again later",
  get_book_link_failed: "Get book link failed",
  update_profile: "Update Profile",
  settings: "Settings",
  change_password: "Change Password",
  logout: "Logout",
  nick_name: "Nickname",
  gender: "Gender",
  Phone: "Phone",
  male: "Male",
  female: "Female",
  language: "Language",
  theme: "Theme",
  new_password: "New password",
  confirm_password: "Confirm password",
  password_is_not_standard:
    "Password must be at least 12 characters, contain at least one uppercase letter, one lowercase letter, one number and one special character.",
  error: "Error",
  alert_empty_password: "Password can not be empty",
  alert_confirm_password: "Confirm password must be the same as new password",
  chatbot_hello:
    "Hi, I am BookPad Chatbot. I can help you to find your favorite books. You can also ask me to recommend you some books. Let's get started!",
  bookpad_chatbot: "BookPad Chatbot",
};
