export const enStrings = {
  app_name: "BookPad",
  success_update_publisher: "Update publisher successfully",
  add_new_publisher: "Add new publisher",
  add_new_book: "Add new book",
  success_create_publisher: "Create publisher successfully",
  filter: "Filter",
  search: "Search",
  author: "Author",
  status: "Status",
  books: "Books",
  add: "Add",
  save: "Save",
  edit: "Edit",
  publisher_name: "Publisher name",
  publisher_description: "Publisher description",
  publisher_name_required: "Publisher name is required",
  publisher_description_required: "Publisher description is required",
  missing_required_fields: "Missing required fields",
  title: "Title",
  publish_date: "Publish date",
  view_and_edit_book: "View and edit book",
  book_description: "Book description",
  add_new_author: "Add new author",
  view_author: "View author",
  edit_author: "Edit author",
  author_date_of_birth: "Author date of birth",
  author_date_of_death: "Author date of death",
  author_description: "Author description",
  author_name: "Author name",
  success_create_author: "Create author successfully",
  success_create_Category: "Create Category successfully",
  category_name: "Category name",
  category_description: "Category description",
  add_new_category: "Add new category",
  edit_category: "Edit category",
  view_category: "View category",
  category_id: "Category id",
  publisher_id: "Publisher id",
  author_id: "Author id",
  delete: "Delete",
  get_started: "Get started",
};
