import type { enStrings } from "./en";

export const viStrings: typeof enStrings = {
  app_name: "BookPad",
  success_update_publisher: "Cập nhật nhà xuất bản thành công",
  add_new_publisher: "Thêm nhà xuất bản mới",
  add_new_book: "Thêm sách mới",
  success_create_publisher: "Tạo nhà xuất bản thành công",
  filter: "Lọc",
  search: "Tìm kiếm",
  author: "Tác giả",
  status: "Trạng thái",
  books: "Sách",
  add: "Thêm",
  save: "Lưu",
  edit: "Sửa",
  publisher_name: "Tên nhà xuất bản",
  publisher_description: "Mô tả nhà xuất bản",
  publisher_name_required: "Tên nhà xuất bản là bắt buộc",
  publisher_description_required: "Mô tả nhà xuất bản là bắt buộc",
  missing_required_fields: "Các trường bắt buộc không đầy đủ",
  title: "Tiêu đề",
  publish_date: "Ngày xuất bản",
  view_and_edit_book: "Xem và sửa sách",
  book_description: "Mô tả sách",
  add_new_author: "Thêm tác giả mới",
  view_author: "Xem tác giả",
  edit_author: "Sửa tác giả",
  author_date_of_birth: "Ngày sinh của tác giả",
  author_date_of_death: "Ngày mất của tác giả",
  author_description: "Mô tả tác giả",
  author_name: "Tên tác giả",
  success_create_author: "Tạo tác giả thành công",
  success_create_Category: "Tạo danh mục thành công",
  category_name: "Tên danh mục",
  category_description: "Mô tả danh mục",
  add_new_category: "Thêm danh mục mới",
  edit_category: "Sửa danh mục",
  view_category: "Xem danh mục",
  category_id: "Mã danh mục",
  publisher_id: "Mã nhà xuất bản",
  author_id: "Mã tác giả",
  delete: "Xóa",
  get_started: "Bắt đầu",
  go_back: "Quay lại",
  user_name: "Tên người dùng",
  password: "Mật khẩu",
  login: "Đăng nhập",
  forgot_password: "Quên mật khẩu",
  dont_have_account: "Không có tài khoản?",
  sign_up: "Đăng ký",
  email: "Email",
  loginSuccess: "Đăng nhập thành công",
  loginSuccessMessage: "Bạn đã đăng nhập thành công",
  ok: "Đồng ý",
  loginFailed: "Đăng nhập thất bại",
  hello: "Xin chào",
  for_you: "Dành cho bạn",
  best_sellers: "Sách bán chạy nhất",
  new_releases: "Sách mới phát hành",
  categories: "Danh mục",
  authors: "Tác giả",
  publishers: "Nhà xuất bản",
  retry: "Thử lại",
  exit: "Thoát",
  read: "Đọc",
  book_detail: "Chi tiết sách",
  error_occurred: "Đã xảy ra lỗi. Vui lòng thử lại sau",
  get_book_link_failed: "Lấy liên kết sách thất bại",
  update_profile: "Cập nhật hồ sơ",
  settings: "Cài đặt",
  change_password: "Đổi mật khẩu",
  logout: "Đăng xuất",
  nick_name: "Biệt danh",
  gender: "Giới tính",
  Phone: "Số điện thoại",
  male: "Nam",
  female: "Nữ",
  language: "Ngôn ngữ",
  theme: "Giao diện",
  new_password: "Mật khẩu mới",
  confirm_password: "Xác nhận mật khẩu",
  password_is_not_standard:
    "Mật khẩu phải có ít nhất 12 ký tự, có ít nhất một chữ cái in hoa, một chữ cái in thường, một số và một ký tự đặc biệt.",
  error: "Lỗi",
  alert_empty_password: "Mật khẩu không được để trống",
  alert_confirm_password: "Xác nhận mật khẩu phải giống với mật khẩu mới",
  chatbot_hello:
    "Xin chào, tôi là Chatbot của BookPad. Tôi có thể giúp bạn tìm sách yêu thích của mình. Bạn cũng có thể hỏi tôi để đề xuất cho bạn một số sách. Hãy bắt đầu nào!",
  bookpad_chatbot: "Chatbot của BookPad",
  get_book_self_failed: "Lấy thông tin sách thất bại",
  remove_book_from_library_success: "Xóa sách khỏi thư viện thành công",
  remove_book_from_library_failed: "Xóa sách khỏi thư viện thất bại",
  add_book_to_library_success: "Thêm sách vào thư viện thành công",
  add_book_to_library_failed: "Thêm sách vào thư viện thất bại",
  empty_data: "Không có dữ liệu",
  reviews: "Đánh giá",
  no_reviews: "Không có đánh giá nào",
  create_review: "Gửi đánh giá",
  write_review: "Gửi đánh giá",
  how_would_you_rate: "Bạn thấy cuốn sách này như thế nào?",
  send_review: "Gửi đánh giá",
  write_your_review: "Viết đánh giá của bạn",
  createReviewSuccess: "Gửi đánh giá thành công",
  delete_review: "Xóa đánh giá",
  delete_review_confirm: "Bạn chắc chắn muốn xóa đánh giá này?",
  cancel: "Hủy",
  i_cant_find_suitable_books_for_you:
    "Xin lỗi. Tôi không tìm được sách phù hợp cho bạn.",
  that_is_all: "Đó là toàn bộ những gì tôi tìm được",
  send: "Gửi",
  upload: "Tải lên",
  upload_image: "Tải ảnh lên",
  upload_image_succes: "Tải ảnh lên thành công",
  profile: "Cá nhân",
  upload_image_fail: "Tải ảnh lên thất bại",
  reading: "Đang đọc",
  wish_listed_books: "Đã lưu",
  sorry_im_busy: "Sorry. I'm busy now. Please try again later",
};
